### ISSUE TITLE
can not start the server

### ISSUE THREAD

**Issue by zshankang** [norkator/Poker-Pocket-Backend#1]
fs.readFileSync(ranksFile) buffer error.
RangErr,out of Rang

**Comment by norkator** [comment]
Aah yes I have forgotten ranks file (big file) need to upload it somewhere and update readme instructions. I check this later today.

**Comment by zshankang** [comment]
I downloaded the file HandRanks.dat and put it in the app directory. At startup, it appears
internal / buffer.js: 76
   throw new ERR_OUT_OF_RANGE (type || 'offset',
   ^

RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be
  > = 0 and <= 7970379. Received 23028288
[90m at boundsError (internal / buffer.js: 76: 9) [39m
[90m at Buffer.readUInt32LE (internal / buffer.js: 210: 5) [39m

I want to know what this .dat file is and what it does

**Comment by norkator** [comment]
Its used to evaluate cards to find hand values for each player.

**Comment by zshankang** [comment]
Oh, OK. I would like to ask, in each round, how does each round identify the current round, what operations have been done, and what kind of information should be sent to each player?

**Comment by norkator** [comment]
No much time to answer this broadly but backend is responsible for knowing room current state. Also backend is throwing status data all time thru websocket to room connected front ends.

**Comment by norkator** [comment]
I close this
