### ISSUE TITLE
how to change from postgres to my sql

### ISSUE THREAD

**Issue by MrSnailman** [norkator/poker-pocket-backend#13]
I need a walkthrough please on how to do that on this specific app because i have never used sequilize or whaterever that is

**Comment by bitcoinbrisbane** [comment]
The project uses Sequelize which is a JS Orm.  You should just be able to change your connection string and dialect and it should work.

https://github.com/norkator/poker-pocket-backend/blob/master/database/sequelize.js#L16

**Comment by norkator** [comment]
I think I will set this up running again, change license and update documentation regarding changing database. Thanks @bitcoinbrisbane for input.

**Comment by bitcoinbrisbane** [comment]
> I think I will set this up running again, change license and update documentation regarding changing database. Thanks @bitcoinbrisbane for input.

Not a problem, let me know if you need any help.
