### ISSUE TITLE
Further developments

### ISSUE THREAD

**Issue by AlexTracks** [norkator/poker-pocket-backend#26]
Good afternoon, will there be any further developments? Refactoring? Improvements?

**Comment by norkator** [comment]
> Good afternoon, will there be any further developments? Refactoring? Improvements?

From me no since I don't see any use for this at my side. You are free to improve and develop features if you like. I will keep this open source and host sample version of it. If you do something I can review and try out for the fun of it.

Any other questions?

**Comment by norkator** [comment]
> Could you share the code for the Android app 'app'? I would like to explore it. Thank you in advance.

That Android app is not open source.

**Comment by norkator** [comment]
> > Could you share the code for the Android app 'app'? I would like to explore it. Thank you in advance.
> 
> That Android app is not open source.

I can think about making cleaned clone of it. I need to clean all sensitive stuff away and dump it to new repository to get rid of commit history.

**Comment by AlexTracks** [comment]
I think that would be great. Please make time for it.)

> > > Could you share the code for the Android app 'app'? I would like to explore it. Thank you in advance.
> > 
> > 
> > That Android app is not open source.
> 
> I can think about making cleaned clone of it. I need to clean all sensitive stuff away and dump it to new repository to get rid of commit history.

I think that would be great. Please make time for it.)

**Comment by norkator** [comment]
@AlexTracks source is now here https://github.com/norkator/poker-pocket-android

**Comment by norkator** [comment]
I assume this if fine. Closing..
