### ISSUE TITLE
Request for Assistance - Modifying backend or client

### ISSUE THREAD

**Issue by oran12com** [norkator/poker-pocket-backend#28]
Hello,

We are currently working on modifying a Texas Hold'em game in the poker project, but we want to implement a different version of poker, specifically Dük Poker.

Here’s what we are trying to achieve:

At the start of the game, each player is dealt one open card and one closed card. Players can see one of each other’s cards.
After this, the first betting round begins.
Then, each player is dealt another open card, followed by a second betting round.
Again, another open card is dealt to each player, and another betting round occurs.
This continues until each player has four open cards and one closed card.
Finally, the showdown happens, and the player with the strongest hand wins.
There are no shared community cards; each player’s hand is entirely made up of their own cards, and the sequence continues with betting rounds between each card dealt. We tried making these changes in both the backend and client code, but the modifications don’t seem to reflect properly in the game.

Could you assist us with implementing these changes? We are open to paying for your time and assistance if needed.

Thank you for your help!

Best regards,

**Comment by norkator** [comment]
I would start from scratch if I would do that.
